version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Group all minor and patch updates together
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Set reviewers for pull requests
    reviewers:
      - "kenzycodex"
    # Limit the number of open pull requests Dependabot can have
    open-pull-requests-limit: 10
    # Allow up to 5 dependencies to be upgraded in each pull request
    pull-request-branch-name:
      # Use a prefix for the branch name
      separator: "/"
    # Add labels to pull requests
    labels:
      - "dependencies"
      - "automated"
    # Ignore certain dependencies that might cause issues or need manual review
    ignore:
      # Ignore major updates to these packages as they may contain breaking changes
      - dependency-name: "@fortawesome/fontawesome-free"
        update-types: ["version-update:semver-major"]
      - dependency-name: "remixicon"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "kenzycodex"
    labels:
      - "ci-cd"
      - "dependencies"
      - "automated"