name: Release & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'
          # Removed cache option
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
      
      - name: Build package
        run: npm run build
      
      - name: Generate release notes
        id: release-notes
        run: |
          # Get the tag name
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          
          # Try to get previous tag, if it fails use a simpler approach
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 $CURRENT_TAG^ 2>/dev/null || echo "")
          
          if [ -z "$PREVIOUS_TAG" ]; then
            # If there's no previous tag, just get all commits up to current tag
            NOTES=$(git log --pretty=format:"- %s" --no-merges $CURRENT_TAG)
          else
            # Generate release notes based on commits between tags
            NOTES=$(git log $PREVIOUS_TAG..$CURRENT_TAG --pretty=format:"- %s" --no-merges)
          fi
          
          # Save release notes to file
          echo "$NOTES" > release-notes.md
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release-notes.md
          files: |
            LICENSE
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Build Storybook
        run: npm run build-storybook
      
      - name: Deploy Storybook to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          branch: gh-pages